version: "3"

networks:
    minha-rede:
      driver: bridge

services:
#docker run -d --name mysql-db -p 3306:3306 --network minha-rede -e MYSQL_ROOT_PASSWORD=root mysql:5.6
  mysql-db:
    image: mysql:5.6
    container_name: mysql-db
    ports:
      - "3306:3306"
    networks:
      - minha-rede
    environment:
      - "MYSQL_ROOT_PASSWORD=root"

#docker run -d --network minha-rede --name carros-api-docker -p 8080:8080 carros-api/carros-api:latest
  carros-api-rest:
    build:
      dockerfile: ./dockerfile
      context: .
    image: carros-api/carros-api
    container_name: carros-api-rest
    ports:
      - "8080:8080"
    networks:
      - minha-rede
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    depends_on:
      - "mysql-db"


#####--- Compilar e rodar este arquivo no terminal ---#####
#docker-compose build
#docker-compose up -d